module.exports = [
  { id: 1, imageUrl: "www.google.com", name: "Myanmar" },
  { id: 2, imageUrl: "www.google.com", name: "Thailand" },
  { id: 3, imageUrl: "www.google.com", name: "Singapore" },
  { id: 4, imageUrl: "www.google.com", name: "Malaysia" },
  { id: 5, imageUrl: "www.google.com", name: "Vietnam" },
  { id: 6, imageUrl: "www.google.com", name: "Cambodia" },
  { id: 7, imageUrl: "www.google.com", name: "Laos" },
  { id: 8, imageUrl: "www.google.com", name: "China Mainland" },
  { id: 9, imageUrl: "www.google.com", name: "China Taiwan" },
  { id: 10, imageUrl: "www.google.com", name: "China HongKong" },
  { id: 11, imageUrl: "www.google.com", name: "South Korea" },
  { id: 12, imageUrl: "www.google.com", name: "Japan" },
  { id: 13, imageUrl: "www.google.com", name: "Dubai (UAE)" },
  { id: 14, imageUrl: "www.google.com", name: "Australia" },
  { id: 15, imageUrl: "www.google.com", name: "Indonesia" },
  { id: 16, imageUrl: "www.google.com", name: "Philippines" },
  { id: 17, imageUrl: "www.google.com", name: "India" },
  { id: 18, imageUrl: "www.google.com", name: "US" },
];
