module.exports = [
  { imageUrl: "www.google.com", name: "Myanmar" },
  { imageUrl: "www.google.com", name: "Thailand" },
  { imageUrl: "www.google.com", name: "Singapore" },
  { imageUrl: "www.google.com", name: "Malaysia" },
  { imageUrl: "www.google.com", name: "Vietnam" },
  { imageUrl: "www.google.com", name: "Cambodia" },
  { imageUrl: "www.google.com", name: "Laos" },
  { imageUrl: "www.google.com", name: "China Mainland" },
  { imageUrl: "www.google.com", name: "China Taiwan" },
  { imageUrl: "www.google.com", name: "China HongKong" },
  { imageUrl: "www.google.com", name: "South Korea" },
  { imageUrl: "www.google.com", name: "Japan" },
  { imageUrl: "www.google.com", name: "Dubai (UAE)" },
  { imageUrl: "www.google.com", name: "Australia" },
  { imageUrl: "www.google.com", name: "Indonesia" },
  { imageUrl: "www.google.com", name: "Philippines" },
  { imageUrl: "www.google.com", name: "India" },
  { imageUrl: "www.google.com", name: "US" },
];
